<?php

// The OAuth credentials you received when registering your app at Twitter
define("TWITTER_CONSUMER_KEY", "IsWhxki9LvQt7T5CPvq7Q");
define("TWITTER_CONSUMER_SECRET", "z2xk89JODOsdZ37TbqOC6iF75AhcRjl90uPPuCO0");


// The OAuth data for the twitter account
define("OAUTH_TOKEN", "2290201770-xTzcD6VDe62LHMVhkz2KRlkhSFHpve60LBwFGyk");
define("OAUTH_SECRET", "tE8UmHRSZk3nOT3jLoViSHtZhAsrqCxOjqVcq18LUhfPA");

?>